name: dart_template
version: 1.0.0+3
publish_to: none

environment:
  sdk: "3.8.0"

dependencies:
  json_serializable: ^6.6.1
  json_annotation: ^4.8.0
  aws_apigatewaymanagementapi_api: null
  aws_client: ^0.4.1
  aws_cognito_idp_api: null
  aws_common: null
  aws_lambda_dart_runtime: ^1.1.0
  crypto: ^3.0.2
  dartx: ^1.1.0
  googleapis_auth: ^1.3.1
  intl: ^0.18.0
  sentry: ^6.20.1
  shelf:
  shelf_router:
  uuid: ^3.0.7

dev_dependencies:
  build_runner: ^2.3.3
  lints:
