name: dart_template
version: 1.0.0+3
publish_to: none

environment:
  sdk: '>=2.15.1 <3.0.0'

dependencies:
  aws_apigatewaymanagementapi_api: null
  aws_cognito_idp_api: null
  aws_common: null
  aws_dynamodb_api: null
  aws_lambda_dart_runtime: ^1.1.0
  crypto: ^3.0.2
  dartx: ^1.1.0
  googleapis_auth: ^1.3.1
  intl: ^0.18.0
  sentry: ^6.20.1
  shelf:
  shelf_router:

dev_dependencies:
  build_runner:
  lints:
